"use client"

import { useState } from "react"

export const useProducts = () => {
  const [suppliers] = useState([
    {
      _id: "sup1",
      name: "Kigali Artisan Collective",
      username: "@kigali_artisans",
      description: "Traditional Rwandan crafts ✨ Preserving culture through art 🎨",
      image: "🏪",
      rating: 4.8,
      totalReviews: 156,
      location: "Kigali, Rwanda",
      verified: true,
      followers: "12.5K",
      responseTime: "Usually responds within 2 hours",
      categories: ["Arts & Crafts", "Home Decor", "Traditional Items"],
    },
    {
      _id: "sup2",
      name: "Thousand Hills Coffee",
      username: "@thousandhills_coffee",
      description: "Premium single-origin coffee ☕ From farm to cup with love 💚",
      image: "☕",
      rating: 4.9,
      totalReviews: 203,
      location: "Nyungwe, Rwanda",
      verified: true,
      followers: "8.2K",
      responseTime: "Usually responds within 1 hour",
      categories: ["Coffee", "Beverages", "Organic Products"],
    },
  ])

  const [products] = useState([
    {
      _id: "1",
      name: "Handwoven Agaseke Basket",
      description: "Traditional Rwandan peace basket ✨ Each piece tells a story of unity 🕊️",
      price: 45.99,
      originalPrice: 65.99,
      stockQuantity: 25,
      category: "Arts & Crafts",
      image: "🧺",
      supplierId: "sup1",
      supplierName: "Kigali Artisan Collective",
      rating: 4.8,
      totalReviews: 34,
      views: 1240,
      likes: 892,
      shares: 156,
      trending: true,
      discount: 30,
      xpReward: 25,
    },
    {
      _id: "2",
      name: "Rwandan Coffee Beans",
      description: "Premium Arabica coffee ☕ Wake up to the taste of Rwanda! ☀️",
      price: 28.5,
      originalPrice: 35.0,
      stockQuantity: 35,
      category: "Food & Beverages",
      image: "☕",
      supplierId: "sup2",
      supplierName: "Thousand Hills Coffee",
      rating: 4.9,
      totalReviews: 67,
      views: 2150,
      likes: 1456,
      shares: 234,
      trending: true,
      discount: 19,
      xpReward: 30,
    },
    {
      _id: "3",
      name: "Imigongo Art Painting",
      description: "Traditional geometric art 🎨 Ancient meets modern style ✨",
      price: 125.0,
      originalPrice: 150.0,
      stockQuantity: 8,
      category: "Arts & Crafts",
      image: "🎨",
      supplierId: "sup1",
      supplierName: "Kigali Artisan Collective",
      rating: 4.7,
      totalReviews: 23,
      views: 890,
      likes: 567,
      shares: 89,
      trending: false,
      discount: 17,
      xpReward: 40,
    },
  ])

  return { products, suppliers }
}
